# Generated by Django 3.1 on 2020-08-17 11:34

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', general.models.AccountManager()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_institution',
            field=models.BooleanField(default=False, verbose_name='Institution'),
        ),
    ]
