# Generated by Django 3.1 on 2020-08-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20200818_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
